/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/register": {
    /** Register user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description Register success */
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/api/auth/login": {
    /** Login user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Login success */
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/api/auth/refresh": {
    /** Refresh access token */
    post: {
      requestBody: {
        content: {
          "application/json": {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Refresh success */
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/api/products": {
    /** List current user's products */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Product list */
        200: {
          content: {
            "application/json": components["schemas"]["ProductListResponse"];
          };
        };
      };
    };
    /** Create product */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateProductRequest"];
        };
      };
      responses: {
        /** @description Product created */
        200: {
          content: {
            "application/json": components["schemas"]["CreateProductResponse"];
          };
        };
      };
    };
  };
  "/api/products/{productId}": {
    /** Get product detail */
    get: {
      parameters: {
        path: {
          productId: components["parameters"]["ProductId"];
        };
      };
      responses: {
        /** @description Product detail */
        200: {
          content: {
            "application/json": components["schemas"]["ProductDetailResponse"];
          };
        };
      };
    };
    /** Update product */
    patch: {
      parameters: {
        path: {
          productId: components["parameters"]["ProductId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateProductRequest"];
        };
      };
      responses: {
        /** @description Product updated */
        200: {
          content: {
            "application/json": components["schemas"]["ProductDetailResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks": {
    /** List current user's video tasks */
    get: {
      parameters: {
        query?: {
          status?: components["schemas"]["VideoTaskStatus"];
          productId?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Task list */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskListResponse"];
          };
        };
      };
    };
    /**
     * Create video generation task
     * @description 创建视频任务时预扣 1 次成片额度。
     * Java 创建 task 后调用 Python AI Orchestrator 启动第一阶段工作流。
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateVideoTaskRequest"];
        };
      };
      responses: {
        /** @description Task created */
        200: {
          content: {
            "application/json": components["schemas"]["CreateVideoTaskResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}": {
    /** Get task status and detail */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Task detail */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskDetailResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/plans": {
    /** Get generated video plans */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Video plans */
        200: {
          content: {
            "application/json": components["schemas"]["VideoPlanListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/select-plan": {
    /**
     * Select a video plan
     * @description 用户选择一个视频方案后，Java 保存 selectedPlanId，
     * 然后调用 Python AI 服务启动第二阶段脚本、分镜、素材生成工作流。
     */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            planId: string;
          };
        };
      };
      responses: {
        /** @description Plan selected */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/retry": {
    /** Retry failed task */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Retry accepted */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/assets": {
    /** List task assets */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Asset list */
        200: {
          content: {
            "application/json": components["schemas"]["TaskAssetListResponse"];
          };
        };
      };
    };
    /** Add asset to task */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateAssetRequest"];
        };
      };
      responses: {
        /** @description Asset created */
        200: {
          content: {
            "application/json": components["schemas"]["TaskAssetListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/assets/{assetId}/role": {
    /** Update asset role */
    patch: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
          assetId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateAssetRoleRequest"];
        };
      };
      responses: {
        /** @description Role updated */
        200: {
          content: {
            "application/json": components["schemas"]["TaskAssetListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/assets/confirm": {
    /** Confirm assets */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConfirmAssetsRequest"];
        };
      };
      responses: {
        /** @description Assets confirmed */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/creative-state": {
    /** Get creative state */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Creative state */
        200: {
          content: {
            "application/json": components["schemas"]["CreativeStateResponse"];
          };
        };
      };
    };
    /** Update creative state */
    patch: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateCreativeStateRequest"];
        };
      };
      responses: {
        /** @description Creative state updated */
        200: {
          content: {
            "application/json": components["schemas"]["CreativeStateResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/confirm-plan": {
    /** Confirm video plan and proceed to storyboard generation */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConfirmPlanRequest"];
        };
      };
      responses: {
        /** @description Plan confirmed */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/confirm-storyboard": {
    /** Confirm storyboard and proceed to keyframe configuration */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Storyboard confirmed */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/keyframes": {
    /** List keyframes */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Keyframe list */
        200: {
          content: {
            "application/json": components["schemas"]["KeyframeListResponse"];
          };
        };
      };
    };
    /** Add keyframe (user upload or AI request) */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateKeyframeRequest"];
        };
      };
      responses: {
        /** @description Keyframe created */
        200: {
          content: {
            "application/json": components["schemas"]["KeyframeListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/keyframes/generate": {
    /** Generate AI keyframes for unconfigured storyboard shots */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Keyframe generation triggered */
        200: {
          content: {
            "application/json": components["schemas"]["KeyframeListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/keyframes/{keyframeId}/confirm": {
    /** Confirm a keyframe */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
          keyframeId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConfirmKeyframeRequest"];
        };
      };
      responses: {
        /** @description Keyframe confirmed */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/keyframes/{keyframeId}/reject": {
    /** Reject a keyframe */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
          keyframeId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConfirmKeyframeRequest"];
        };
      };
      responses: {
        /** @description Keyframe rejected */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/keyframes/{keyframeId}/regenerate": {
    /** Regenerate a rejected or failed keyframe */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
          keyframeId: string;
        };
      };
      responses: {
        /** @description Keyframe regeneration triggered */
        200: {
          content: {
            "application/json": components["schemas"]["KeyframeListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/video-clips": {
    /** List video clips */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Video clip list */
        200: {
          content: {
            "application/json": components["schemas"]["VideoClipListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/video-clips/{clipId}/confirm": {
    /** Confirm a video clip */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
          clipId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConfirmVideoClipRequest"];
        };
      };
      responses: {
        /** @description Clip confirmed */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/video-clips/{clipId}/reject": {
    /** Reject a video clip */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
          clipId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConfirmVideoClipRequest"];
        };
      };
      responses: {
        /** @description Clip rejected */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/render": {
    /** Request video render from confirmed clips */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Render requested */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/approve": {
    /** Approve final video review */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Final video approved */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/feedback": {
    /** Submit feedback for repair */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["FeedbackRequest"];
        };
      };
      responses: {
        /** @description Feedback received */
        200: {
          content: {
            "application/json": components["schemas"]["RepairEventListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/repair-events": {
    /** List repair events for a task */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Repair event list */
        200: {
          content: {
            "application/json": components["schemas"]["RepairEventListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/storyboard": {
    /** Get storyboard by task */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Storyboard detail */
        200: {
          content: {
            "application/json": components["schemas"]["StoryboardResponse"];
          };
        };
      };
    };
  };
  "/api/storyboards/{storyboardId}": {
    /** Update storyboard text fields */
    patch: {
      parameters: {
        path: {
          storyboardId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateStoryboardRequest"];
        };
      };
      responses: {
        /** @description Storyboard updated */
        200: {
          content: {
            "application/json": components["schemas"]["StoryboardResponse"];
          };
        };
      };
    };
  };
  "/api/videos": {
    /** List current user's videos */
    get: {
      parameters: {
        query?: {
          productId?: string;
          status?: components["schemas"]["VideoStatus"];
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Video list */
        200: {
          content: {
            "application/json": components["schemas"]["VideoListResponse"];
          };
        };
      };
    };
  };
  "/api/videos/{videoId}": {
    /** Get video detail */
    get: {
      parameters: {
        path: {
          videoId: components["parameters"]["VideoId"];
        };
      };
      responses: {
        /** @description Video detail */
        200: {
          content: {
            "application/json": components["schemas"]["VideoDetailResponse"];
          };
        };
      };
    };
  };
  "/api/videos/{videoId}/export": {
    /** Mark video as exported and return download URL */
    post: {
      parameters: {
        path: {
          videoId: components["parameters"]["VideoId"];
        };
      };
      responses: {
        /** @description Export success */
        200: {
          content: {
            "application/json": components["schemas"]["VideoExportResponse"];
          };
        };
      };
    };
  };
  "/api/storage/presigned-upload-url": {
    /** Get COS presigned upload URL */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["PresignedUploadRequest"];
        };
      };
      responses: {
        /** @description Upload URL */
        200: {
          content: {
            "application/json": components["schemas"]["PresignedUploadResponse"];
          };
        };
      };
    };
  };
  "/api/quotas/me": {
    /** Get current user's quota */
    get: {
      responses: {
        /** @description Quota detail */
        200: {
          content: {
            "application/json": components["schemas"]["UserQuotaResponse"];
          };
        };
      };
    };
  };
  "/api/ai-callbacks/{taskId}": {
    /** Python AI callback */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AiCallbackRequest"];
        };
      };
      responses: {
        /** @description Callback accepted */
        200: {
          content: {
            "application/json": components["schemas"]["CallbackResponse"];
          };
        };
      };
    };
  };
  "/api/render-callbacks/{taskId}": {
    /** Render Worker callback */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RenderCallbackRequest"];
        };
      };
      responses: {
        /** @description Callback accepted */
        200: {
          content: {
            "application/json": components["schemas"]["CallbackResponse"];
          };
        };
      };
    };
  };
  "/api/admin/video-tasks": {
    /** Admin list all video tasks */
    get: {
      responses: {
        /** @description Admin task list */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/model-logs": {
    /** Admin list model logs */
    get: {
      responses: {
        /** @description Model logs */
        200: {
          content: {
            "application/json": components["schemas"]["ModelLogListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/render-logs": {
    /** Admin list render logs */
    get: {
      responses: {
        /** @description Render logs */
        200: {
          content: {
            "application/json": components["schemas"]["RenderLogListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/users": {
    /** Admin list all users */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          status?: string;
        };
      };
      responses: {
        /** @description Admin user list */
        200: {
          content: {
            "application/json": components["schemas"]["AdminUserListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/videos": {
    /** Admin list all videos */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          status?: components["schemas"]["VideoStatus"];
          productId?: string;
        };
      };
      responses: {
        /** @description Admin video list */
        200: {
          content: {
            "application/json": components["schemas"]["AdminVideoListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/quotas": {
    /** Admin list user quotas */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          status?: string;
        };
      };
      responses: {
        /** @description Admin quota list */
        200: {
          content: {
            "application/json": components["schemas"]["AdminQuotaListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/quotas/{userId}": {
    /** Admin update user quota limits */
    patch: {
      parameters: {
        path: {
          userId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AdminQuotaUpdateRequest"];
        };
      };
      responses: {
        /** @description Updated user quota */
        200: {
          content: {
            "application/json": components["schemas"]["AdminQuotaDetailResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ApiResponse: {
      /** @example 0 */
      code?: number;
      /** @example success */
      message?: string;
      data?: unknown;
    };
    ErrorDetail: {
      errorCode: string;
      errorMessage: string;
      failedStage: string;
      retryable: boolean;
      provider?: string | null;
      /** @description Internal diagnostics for admin views only. */
      rawError?: Record<string, unknown> | null;
    };
    PageMeta: {
      page?: number;
      pageSize?: number;
      total?: number;
      totalPages?: number;
    };
    /** @enum {string} */
    VideoType: "pain_point_solution" | "before_after" | "review" | "product_showcase" | "ugc_style" | "tutorial";
    /** @enum {string} */
    VideoTaskStatus: "draft" | "asset_uploading" | "asset_analyzing" | "waiting_asset_confirmation" | "reference_analyzing" | "plan_generating" | "analyzing" | "analysis_completed" | "plan_generated" | "waiting_plan_selection" | "storyboard_generating" | "script_generating" | "script_generated" | "material_generating" | "material_generated" | "rendering" | "checking" | "completed" | "failed" | "exported" | "waiting_storyboard_confirmation" | "keyframe_configuring" | "image_generating" | "waiting_image_confirmation" | "video_clip_generating" | "waiting_video_clip_confirmation" | "waiting_final_review" | "repairing" | "cancelled";
    /** @enum {string} */
    TaskMode: "PRODUCT_CREATIVE" | "REFERENCE_STORYBOARD" | "USER_SCRIPT" | "CUSTOM_STORYBOARD";
    /** @enum {string} */
    VideoStatus: "completed" | "exported" | "deleted";
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    AuthResponse: {
      /** @example 0 */
      code?: number;
      /** @example success */
      message?: string;
      data?: {
        /** Format: uuid */
        userId?: string;
        accessToken?: string;
        refreshToken?: string;
      };
    };
    CreateProductRequest: {
      name: string;
      description?: string;
      productLink?: string;
      /** @description Optional for non-product-first Fashion Creative Loop modes. Product creative mode should still provide at least one product image. */
      imageUrls?: string[];
      /** @example US */
      targetMarket: string;
      /** @example en */
      language: string;
    };
    UpdateProductRequest: {
      name?: string;
      description?: string;
      sellingPoints?: string[];
      painPoints?: string[];
      targetAudience?: string[];
      scenes?: string[];
    };
    CreateProductResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        productId?: string;
      };
    };
    Product: {
      /** Format: uuid */
      id?: string;
      name?: string;
      description?: string;
      productLink?: string;
      category?: string;
      targetMarket?: string;
      language?: string;
      sellingPoints?: string[];
      painPoints?: string[];
      targetAudience?: string[];
      scenes?: string[];
      videoScore?: number;
      riskTips?: string[];
      imageUrls?: string[];
    };
    ProductDetailResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["Product"];
    };
    ProductListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["Product"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    CreateVideoTaskRequest: {
      /** Format: uuid */
      productId: string;
      /** @enum {integer} */
      duration: 15 | 20 | 25 | 30;
      /** @description Legacy video structure hint. Optional for Fashion Creative Loop modes; AI creative_plan will produce the actual structure candidates. */
      videoType?: components["schemas"]["VideoType"];
      /** @default true */
      needSubtitles?: boolean;
      /** @default false */
      needVoiceover?: boolean;
      taskMode?: components["schemas"]["TaskMode"];
      productCategory?: string | null;
      shotCount?: number | null;
    };
    CreateVideoTaskResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        status?: components["schemas"]["VideoTaskStatus"];
        progress?: number;
      };
    };
    VideoTask: {
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      productId?: string;
      status?: components["schemas"]["VideoTaskStatus"];
      progress?: number;
      duration?: number;
      videoType?: components["schemas"]["VideoType"];
      needSubtitles?: boolean;
      needVoiceover?: boolean;
      /** Format: uuid */
      selectedPlanId?: string | null;
      taskMode?: components["schemas"]["TaskMode"];
      productCategory?: string | null;
      shotCount?: number | null;
      currentVersion?: number;
      errorMessage?: string | null;
      errorCode?: string | null;
      failedStage?: string | null;
      errorRetryable?: boolean | null;
      /** @example 1.0.0 */
      manifestVersion?: string;
      /** @example 1.0.0 */
      schemaVersion?: string;
      retryCount?: number;
    };
    VideoTaskDetailResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["VideoTask"];
    };
    VideoTaskStatusResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        status?: components["schemas"]["VideoTaskStatus"];
        progress?: number;
      };
    };
    VideoTaskListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["VideoTask"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    VideoPlan: {
      /** Format: uuid */
      planId?: string;
      type?: components["schemas"]["VideoType"];
      title?: string;
      hook?: string;
      structure?: string;
      reason?: string;
      estimatedDuration?: number;
      score?: number;
    };
    VideoPlanListResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        plans?: components["schemas"]["VideoPlan"][];
      };
    };
    StoryboardShot: {
      shotNo?: number;
      duration?: number;
      scene?: string;
      action?: string;
      subtitle?: string;
      materialType?: string;
      prompt?: string;
      editInstruction?: string;
    };
    Storyboard: {
      /** Format: uuid */
      storyboardId?: string;
      title?: string;
      hook?: string;
      script?: string;
      coverText?: string;
      caption?: string;
      hashtags?: string[];
      musicSuggestion?: string;
      shots?: components["schemas"]["StoryboardShot"][];
    };
    StoryboardResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["Storyboard"];
    };
    UpdateStoryboardRequest: {
      title?: string;
      hook?: string;
      coverText?: string;
      caption?: string;
      hashtags?: string[];
      shots?: components["schemas"]["StoryboardShot"][];
    };
    Video: {
      /** Format: uuid */
      videoId?: string;
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      productId?: string;
      title?: string;
      videoUrl?: string;
      coverUrl?: string;
      duration?: number;
      resolution?: string;
      qualityScore?: number;
      riskScore?: number;
      caption?: string;
      hashtags?: string[];
      status?: components["schemas"]["VideoStatus"];
    };
    VideoDetailResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["Video"];
    };
    VideoListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["Video"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    VideoExportResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        videoId?: string;
        status?: components["schemas"]["VideoStatus"];
        downloadUrl?: string;
      };
    };
    PresignedUploadRequest: {
      fileName: string;
      mimeType: string;
      sizeBytes: number;
      contentMd5?: string | null;
      /** @enum {string} */
      folder: "product-images" | "ai-images" | "ai-clips" | "final-videos" | "covers";
      /** Format: uuid */
      productId?: string | null;
      /** Format: uuid */
      taskId?: string | null;
    };
    PresignedUploadResponse: {
      code?: number;
      message?: string;
      data?: {
        uploadUrl?: string;
        fileUrl?: string;
      };
    };
    UserQuotaResponse: {
      code?: number;
      message?: string;
      data?: {
        videoQuota?: number;
        imageQuota?: number;
        videoClipQuota?: number;
        exportQuota?: number;
        usedVideoCount?: number;
        usedImageCount?: number;
        usedVideoClipCount?: number;
        usedExportCount?: number;
        /**
         * Format: date
         * @description Natural day for the current usage counters. Usage resets when this date changes.
         */
        quotaDate?: string;
      };
    };
    AiCallbackRequest: {
      /** Format: uuid */
      taskId: string;
      /** @example 1.0.0 */
      schemaVersion: string;
      /** @enum {string} */
      stage: "asset_analysis" | "reference_analysis" | "creative_plan" | "product_analysis" | "video_plan" | "storyboard" | "material" | "quality_check" | "render_manifest" | "keyframe" | "video_clip" | "qa" | "repair";
      /** @enum {string} */
      status: "success" | "failed";
      nextTaskStatus?: components["schemas"]["VideoTaskStatus"];
      fashionAssetAnalysis?: Record<string, unknown> | null;
      referenceAnalysis?: Record<string, unknown> | null;
      productAnalysis?: Record<string, unknown> | null;
      plans?: Record<string, never>[] | null;
      storyboard?: Record<string, unknown> | null;
      materials?: Record<string, never>[] | null;
      renderManifest?: Record<string, unknown> | null;
      qualityCheck?: Record<string, unknown> | null;
      keyframes?: Record<string, never>[] | null;
      clips?: Record<string, never>[] | null;
      qaResult?: Record<string, unknown> | null;
      repairResult?: Record<string, unknown> | null;
      error?: components["schemas"]["ErrorDetail"] | null;
    };
    RenderCallbackRequest: {
      /** Format: uuid */
      taskId: string;
      /**
       * Format: uuid
       * @description Required when status is completed.
       */
      videoId?: string | null;
      renderTaskId?: string | null;
      /** @example 1.0.0 */
      manifestVersion?: string;
      /** @enum {string} */
      status: "completed" | "failed";
      videoUrl?: string | null;
      coverUrl?: string | null;
      duration?: number | null;
      resolution?: string | null;
      renderLog?: Record<string, unknown> | null;
      error?: components["schemas"]["ErrorDetail"] | null;
    };
    CallbackResponse: {
      /** @example 0 */
      code?: number;
      /** @example received */
      message?: string;
      data?: {
        received?: boolean;
      };
    };
    ModelLogListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: Record<string, never>[];
        total?: number;
      };
    };
    RenderLogListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: Record<string, never>[];
        total?: number;
      };
    };
    UserItem: {
      /** Format: uuid */
      id?: string;
      /** Format: email */
      email?: string;
      role?: string;
      status?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    AdminUserListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["UserItem"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    AdminVideoListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["Video"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    AdminQuotaItem: {
      /** Format: uuid */
      userId?: string;
      /** Format: email */
      email?: string;
      role?: string;
      status?: string;
      videoQuota?: number;
      imageQuota?: number;
      videoClipQuota?: number;
      exportQuota?: number;
      usedVideoCount?: number;
      usedImageCount?: number;
      usedVideoClipCount?: number;
      usedExportCount?: number;
      /** Format: date */
      quotaDate?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    AdminQuotaUpdateRequest: {
      videoQuota?: number;
      imageQuota?: number;
      videoClipQuota?: number;
      exportQuota?: number;
    };
    AdminQuotaListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["AdminQuotaItem"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    AdminQuotaDetailResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["AdminQuotaItem"];
    };
    TaskAsset: {
      /** Format: uuid */
      assetId?: string;
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      productId?: string | null;
      /** Format: uuid */
      shotId?: string | null;
      /** @enum {string} */
      assetKind?: "image" | "video" | "audio";
      url?: string;
      /** @enum {string} */
      assetRole?: "product_front" | "product_back" | "product_detail" | "model_reference" | "scene_reference" | "outfit_reference" | "reference_video" | "user_keyframe" | "generated_result" | "ai_keyframe" | "image_variant" | "video_clip" | "final_video" | "cover_image";
      /** @enum {string} */
      source?: "user_upload" | "ai_generated" | "external_url";
      fileName?: string | null;
      mimeType?: string | null;
      sizeBytes?: number | null;
      description?: string | null;
      metadata?: Record<string, unknown> | null;
      confirmed?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    CreativeState: {
      /** Format: uuid */
      creativeStateId?: string;
      /** Format: uuid */
      taskId?: string;
      product?: Record<string, unknown> | null;
      model?: Record<string, unknown> | null;
      scene?: Record<string, unknown> | null;
      outfit?: Record<string, unknown> | null;
      referenceVideo?: Record<string, unknown> | null;
      constraints?: Record<string, unknown> | null;
      userRequirements?: Record<string, unknown> | null;
      version?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Keyframe: {
      /** Format: uuid */
      keyframeId?: string;
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      shotId?: string;
      shotNo?: number;
      /** @enum {string} */
      source?: "user_upload" | "existing_asset" | "ai_generated";
      /** Format: uuid */
      assetId?: string | null;
      /** Format: uuid */
      materialId?: string | null;
      /** @enum {string} */
      imagePurpose?: "first_frame" | "last_frame" | "reference" | "product_detail";
      url?: string | null;
      prompt?: string | null;
      negativePrompt?: string | null;
      provider?: string | null;
      modelName?: string | null;
      /** @enum {string} */
      status?: "draft" | "generating" | "generated" | "uploaded" | "confirmed" | "rejected" | "failed";
      userInstruction?: string | null;
      version?: number;
      errorMessage?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    KeyframeListResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        keyframes?: components["schemas"]["Keyframe"][];
      };
    };
    ConfirmKeyframeRequest: {
      confirmed: boolean;
      feedback?: string;
    };
    VideoClip: {
      /** Format: uuid */
      clipId?: string;
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      shotId?: string;
      /** Format: uuid */
      keyframeId?: string | null;
      shotNo?: number;
      /** @enum {string} */
      source?: "user_upload" | "ai_generated";
      url?: string | null;
      prompt?: string | null;
      negativePrompt?: string | null;
      provider?: string | null;
      modelName?: string | null;
      /** @enum {string} */
      status?: "draft" | "generating" | "generated" | "uploaded" | "confirmed" | "rejected" | "failed";
      duration?: number;
      version?: number;
      errorMessage?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    VideoClipListResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        clips?: components["schemas"]["VideoClip"][];
      };
    };
    ConfirmVideoClipRequest: {
      confirmed: boolean;
      feedback?: string;
    };
    RepairEvent: {
      /** Format: uuid */
      repairEventId?: string;
      /** Format: uuid */
      taskId?: string;
      /** @enum {string} */
      targetType?: "storyboard" | "keyframe" | "video_clip" | "render_manifest" | "final_video" | "plan";
      targetId?: string | null;
      userFeedback?: string;
      issueType?: string | null;
      repairScope?: Record<string, unknown> | null;
      repairPlan?: Record<string, unknown> | null;
      beforeVersion?: number | null;
      afterVersion?: number | null;
      /** @enum {string} */
      status?: "created" | "in_progress" | "completed" | "failed";
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    RepairEventListResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        events?: components["schemas"]["RepairEvent"][];
      };
    };
    FeedbackRequest: {
      feedbackText: string;
      category?: string;
    };
    QaResult: {
      /** Format: uuid */
      qaResultId?: string;
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      userId?: string;
      /** @enum {string} */
      targetType?: "storyboard" | "keyframe" | "video_clip" | "plan" | "final_video";
      targetId?: string | null;
      score?: number | null;
      passed?: boolean;
      issues?: Record<string, unknown> | null;
      suggestions?: string[] | null;
      repairInstruction?: string | null;
      rawAiOutput?: Record<string, unknown> | null;
      /** Format: date-time */
      createdAt?: string;
    };
    VideoFingerprint: {
      /** Format: uuid */
      fingerprintId?: string;
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      productId?: string | null;
      /** Format: uuid */
      userId?: string;
      openingType?: string | null;
      mainAction?: string | null;
      endingType?: string | null;
      mainVisual?: string | null;
      shotSequence?: Record<string, unknown> | null;
      cameraSequence?: Record<string, unknown> | null;
      scenePosition?: Record<string, unknown> | null;
      similarityScore?: number | null;
      comparedWith?: Record<string, unknown> | null;
      rawFingerprint?: Record<string, unknown> | null;
      /** Format: date-time */
      createdAt?: string;
    };
    CreativeStateResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["CreativeState"];
    };
    UpdateCreativeStateRequest: {
      product?: Record<string, never>;
      model?: Record<string, never>;
      scene?: Record<string, never>;
      outfit?: Record<string, never>;
      referenceVideo?: Record<string, never>;
      constraints?: Record<string, never>;
      userRequirements?: Record<string, never>;
    };
    TaskAssetListResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        assets?: components["schemas"]["TaskAsset"][];
      };
    };
    UpdateAssetRoleRequest: {
      /** @enum {string} */
      role: "product_front" | "product_back" | "product_detail" | "model_reference" | "scene_reference" | "outfit_reference" | "reference_video" | "user_keyframe" | "generated_result" | "ai_keyframe" | "image_variant" | "video_clip" | "final_video" | "cover_image";
      /** Format: uuid */
      shotId?: string | null;
    };
    ConfirmAssetsRequest: {
      assetIds?: string[];
    };
    ConfirmPlanRequest: {
      /** Format: uuid */
      planId: string;
    };
    CreateAssetRequest: {
      /** @enum {string} */
      assetKind: "image" | "video" | "audio";
      assetRole: string;
      url: string;
      /** @enum {string} */
      source: "user_upload" | "ai_generated" | "external_url";
      fileName?: string | null;
      mimeType?: string | null;
      sizeBytes?: number | null;
      description?: string | null;
      metadata?: Record<string, unknown> | null;
    };
    CreateKeyframeRequest: {
      shotNo: number;
      /**
       * @default user_upload
       * @enum {string}
       */
      source?: "user_upload" | "existing_asset" | "ai_generated";
      /** Format: uuid */
      assetId?: string | null;
      /**
       * @default first_frame
       * @enum {string}
       */
      imagePurpose?: "first_frame" | "last_frame" | "reference" | "product_detail";
      url?: string | null;
      prompt?: string | null;
      userInstruction?: string | null;
    };
  };
  responses: never;
  parameters: {
    ProductId: string;
    TaskId: string;
    VideoId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
