/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/register": {
    /** Register user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description Register success */
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/api/auth/login": {
    /** Login user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Login success */
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/api/auth/refresh": {
    /** Refresh access token */
    post: {
      requestBody: {
        content: {
          "application/json": {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Refresh success */
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/api/products": {
    /** List current user's products */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Product list */
        200: {
          content: {
            "application/json": components["schemas"]["ProductListResponse"];
          };
        };
      };
    };
    /** Create product */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateProductRequest"];
        };
      };
      responses: {
        /** @description Product created */
        200: {
          content: {
            "application/json": components["schemas"]["CreateProductResponse"];
          };
        };
      };
    };
  };
  "/api/products/{productId}": {
    /** Get product detail */
    get: {
      parameters: {
        path: {
          productId: components["parameters"]["ProductId"];
        };
      };
      responses: {
        /** @description Product detail */
        200: {
          content: {
            "application/json": components["schemas"]["ProductDetailResponse"];
          };
        };
      };
    };
    /** Update product */
    patch: {
      parameters: {
        path: {
          productId: components["parameters"]["ProductId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateProductRequest"];
        };
      };
      responses: {
        /** @description Product updated */
        200: {
          content: {
            "application/json": components["schemas"]["ProductDetailResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks": {
    /** List current user's video tasks */
    get: {
      parameters: {
        query?: {
          status?: components["schemas"]["VideoTaskStatus"];
          productId?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Task list */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskListResponse"];
          };
        };
      };
    };
    /**
     * Create video generation task
     * @description 创建视频任务时预扣 1 次成片额度。
     * Java 创建 task 后调用 Python AI Orchestrator 启动第一阶段工作流。
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateVideoTaskRequest"];
        };
      };
      responses: {
        /** @description Task created */
        200: {
          content: {
            "application/json": components["schemas"]["CreateVideoTaskResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}": {
    /** Get task status and detail */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Task detail */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskDetailResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/plans": {
    /** Get generated video plans */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Video plans */
        200: {
          content: {
            "application/json": components["schemas"]["VideoPlanListResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/select-plan": {
    /**
     * Select a video plan
     * @description 用户选择一个视频方案后，Java 保存 selectedPlanId，
     * 然后调用 Python AI 服务启动第二阶段脚本、分镜、素材生成工作流。
     */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            planId: string;
          };
        };
      };
      responses: {
        /** @description Plan selected */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/retry": {
    /** Retry failed task */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Retry accepted */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskStatusResponse"];
          };
        };
      };
    };
  };
  "/api/video-tasks/{taskId}/storyboard": {
    /** Get storyboard by task */
    get: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      responses: {
        /** @description Storyboard detail */
        200: {
          content: {
            "application/json": components["schemas"]["StoryboardResponse"];
          };
        };
      };
    };
  };
  "/api/storyboards/{storyboardId}": {
    /** Update storyboard text fields */
    patch: {
      parameters: {
        path: {
          storyboardId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateStoryboardRequest"];
        };
      };
      responses: {
        /** @description Storyboard updated */
        200: {
          content: {
            "application/json": components["schemas"]["StoryboardResponse"];
          };
        };
      };
    };
  };
  "/api/videos": {
    /** List current user's videos */
    get: {
      parameters: {
        query?: {
          productId?: string;
          status?: components["schemas"]["VideoStatus"];
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Video list */
        200: {
          content: {
            "application/json": components["schemas"]["VideoListResponse"];
          };
        };
      };
    };
  };
  "/api/videos/{videoId}": {
    /** Get video detail */
    get: {
      parameters: {
        path: {
          videoId: components["parameters"]["VideoId"];
        };
      };
      responses: {
        /** @description Video detail */
        200: {
          content: {
            "application/json": components["schemas"]["VideoDetailResponse"];
          };
        };
      };
    };
  };
  "/api/videos/{videoId}/export": {
    /** Mark video as exported and return download URL */
    post: {
      parameters: {
        path: {
          videoId: components["parameters"]["VideoId"];
        };
      };
      responses: {
        /** @description Export success */
        200: {
          content: {
            "application/json": components["schemas"]["VideoExportResponse"];
          };
        };
      };
    };
  };
  "/api/storage/presigned-upload-url": {
    /** Get COS presigned upload URL */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["PresignedUploadRequest"];
        };
      };
      responses: {
        /** @description Upload URL */
        200: {
          content: {
            "application/json": components["schemas"]["PresignedUploadResponse"];
          };
        };
      };
    };
  };
  "/api/quotas/me": {
    /** Get current user's quota */
    get: {
      responses: {
        /** @description Quota detail */
        200: {
          content: {
            "application/json": components["schemas"]["UserQuotaResponse"];
          };
        };
      };
    };
  };
  "/api/ai-callbacks/{taskId}": {
    /** Python AI callback */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AiCallbackRequest"];
        };
      };
      responses: {
        /** @description Callback accepted */
        200: {
          content: {
            "application/json": components["schemas"]["CallbackResponse"];
          };
        };
      };
    };
  };
  "/api/render-callbacks/{taskId}": {
    /** Render Worker callback */
    post: {
      parameters: {
        path: {
          taskId: components["parameters"]["TaskId"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RenderCallbackRequest"];
        };
      };
      responses: {
        /** @description Callback accepted */
        200: {
          content: {
            "application/json": components["schemas"]["CallbackResponse"];
          };
        };
      };
    };
  };
  "/api/admin/video-tasks": {
    /** Admin list all video tasks */
    get: {
      responses: {
        /** @description Admin task list */
        200: {
          content: {
            "application/json": components["schemas"]["VideoTaskListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/model-logs": {
    /** Admin list model logs */
    get: {
      responses: {
        /** @description Model logs */
        200: {
          content: {
            "application/json": components["schemas"]["ModelLogListResponse"];
          };
        };
      };
    };
  };
  "/api/admin/render-logs": {
    /** Admin list render logs */
    get: {
      responses: {
        /** @description Render logs */
        200: {
          content: {
            "application/json": components["schemas"]["RenderLogListResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ApiResponse: {
      /** @example 0 */
      code?: number;
      /** @example success */
      message?: string;
      data?: unknown;
    };
    ErrorDetail: {
      errorCode: string;
      errorMessage: string;
      failedStage: string;
      retryable: boolean;
      provider?: string | null;
      /** @description Internal diagnostics for admin views only. */
      rawError?: Record<string, unknown> | null;
    };
    PageMeta: {
      page?: number;
      pageSize?: number;
      total?: number;
      totalPages?: number;
    };
    /** @enum {string} */
    VideoType: "pain_point_solution" | "before_after" | "review";
    /** @enum {string} */
    VideoTaskStatus: "draft" | "analyzing" | "analysis_completed" | "plan_generated" | "waiting_plan_selection" | "script_generating" | "script_generated" | "material_generating" | "material_generated" | "rendering" | "checking" | "completed" | "failed" | "exported";
    /** @enum {string} */
    VideoStatus: "completed" | "exported" | "deleted";
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    AuthResponse: {
      /** @example 0 */
      code?: number;
      /** @example success */
      message?: string;
      data?: {
        /** Format: uuid */
        userId?: string;
        accessToken?: string;
        refreshToken?: string;
      };
    };
    CreateProductRequest: {
      name: string;
      description?: string;
      productLink?: string;
      imageUrls: string[];
      /** @example US */
      targetMarket: string;
      /** @example en */
      language: string;
    };
    UpdateProductRequest: {
      name?: string;
      description?: string;
      sellingPoints?: string[];
      painPoints?: string[];
      targetAudience?: string[];
      scenes?: string[];
    };
    CreateProductResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        productId?: string;
      };
    };
    Product: {
      /** Format: uuid */
      id?: string;
      name?: string;
      description?: string;
      productLink?: string;
      category?: string;
      targetMarket?: string;
      language?: string;
      sellingPoints?: string[];
      painPoints?: string[];
      targetAudience?: string[];
      scenes?: string[];
      videoScore?: number;
      riskTips?: string[];
      imageUrls?: string[];
    };
    ProductDetailResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["Product"];
    };
    ProductListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["Product"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    CreateVideoTaskRequest: {
      /** Format: uuid */
      productId: string;
      /** @enum {integer} */
      duration: 15 | 20 | 25 | 30;
      videoType: components["schemas"]["VideoType"];
      /** @default true */
      needSubtitles?: boolean;
      /** @default false */
      needVoiceover?: boolean;
    };
    CreateVideoTaskResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        status?: components["schemas"]["VideoTaskStatus"];
        progress?: number;
      };
    };
    VideoTask: {
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      productId?: string;
      status?: components["schemas"]["VideoTaskStatus"];
      progress?: number;
      duration?: number;
      videoType?: components["schemas"]["VideoType"];
      needSubtitles?: boolean;
      needVoiceover?: boolean;
      /** Format: uuid */
      selectedPlanId?: string | null;
      errorMessage?: string | null;
      errorCode?: string | null;
      failedStage?: string | null;
      errorRetryable?: boolean | null;
      /** @example 1.0.0 */
      manifestVersion?: string;
      /** @example 1.0.0 */
      schemaVersion?: string;
      retryCount?: number;
    };
    VideoTaskDetailResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["VideoTask"];
    };
    VideoTaskStatusResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        status?: components["schemas"]["VideoTaskStatus"];
        progress?: number;
      };
    };
    VideoTaskListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["VideoTask"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    VideoPlan: {
      /** Format: uuid */
      planId?: string;
      type?: components["schemas"]["VideoType"];
      title?: string;
      hook?: string;
      structure?: string;
      reason?: string;
      estimatedDuration?: number;
      score?: number;
    };
    VideoPlanListResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        taskId?: string;
        plans?: components["schemas"]["VideoPlan"][];
      };
    };
    StoryboardShot: {
      shotNo?: number;
      duration?: number;
      scene?: string;
      action?: string;
      subtitle?: string;
      materialType?: string;
      prompt?: string;
      editInstruction?: string;
    };
    Storyboard: {
      /** Format: uuid */
      storyboardId?: string;
      title?: string;
      hook?: string;
      script?: string;
      coverText?: string;
      caption?: string;
      hashtags?: string[];
      musicSuggestion?: string;
      shots?: components["schemas"]["StoryboardShot"][];
    };
    StoryboardResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["Storyboard"];
    };
    UpdateStoryboardRequest: {
      title?: string;
      hook?: string;
      coverText?: string;
      caption?: string;
      hashtags?: string[];
      shots?: components["schemas"]["StoryboardShot"][];
    };
    Video: {
      /** Format: uuid */
      videoId?: string;
      /** Format: uuid */
      taskId?: string;
      /** Format: uuid */
      productId?: string;
      title?: string;
      videoUrl?: string;
      coverUrl?: string;
      duration?: number;
      resolution?: string;
      qualityScore?: number;
      riskScore?: number;
      caption?: string;
      hashtags?: string[];
      status?: components["schemas"]["VideoStatus"];
    };
    VideoDetailResponse: {
      code?: number;
      message?: string;
      data?: components["schemas"]["Video"];
    };
    VideoListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: components["schemas"]["Video"][];
        page?: number;
        pageSize?: number;
        total?: number;
        totalPages?: number;
      };
    };
    VideoExportResponse: {
      code?: number;
      message?: string;
      data?: {
        /** Format: uuid */
        videoId?: string;
        status?: components["schemas"]["VideoStatus"];
        downloadUrl?: string;
      };
    };
    PresignedUploadRequest: {
      fileName: string;
      mimeType: string;
      sizeBytes: number;
      contentMd5?: string | null;
      /** @enum {string} */
      folder: "product-images" | "ai-images" | "ai-clips" | "final-videos" | "covers";
      /** Format: uuid */
      productId?: string | null;
      /** Format: uuid */
      taskId?: string | null;
    };
    PresignedUploadResponse: {
      code?: number;
      message?: string;
      data?: {
        uploadUrl?: string;
        fileUrl?: string;
      };
    };
    UserQuotaResponse: {
      code?: number;
      message?: string;
      data?: {
        videoQuota?: number;
        imageQuota?: number;
        videoClipQuota?: number;
        exportQuota?: number;
        usedVideoCount?: number;
        usedImageCount?: number;
        usedVideoClipCount?: number;
        usedExportCount?: number;
      };
    };
    AiCallbackRequest: {
      /** Format: uuid */
      taskId: string;
      /** @example 1.0.0 */
      schemaVersion: string;
      /** @enum {string} */
      stage: "product_analysis" | "video_plan" | "storyboard" | "material" | "quality_check" | "render_manifest";
      /** @enum {string} */
      status: "success" | "failed";
      nextTaskStatus?: components["schemas"]["VideoTaskStatus"];
      productAnalysis?: Record<string, unknown> | null;
      plans?: Record<string, never>[] | null;
      storyboard?: Record<string, unknown> | null;
      materials?: Record<string, never>[] | null;
      renderManifest?: Record<string, unknown> | null;
      qualityCheck?: Record<string, unknown> | null;
      error?: components["schemas"]["ErrorDetail"] | null;
    };
    RenderCallbackRequest: {
      /** Format: uuid */
      taskId: string;
      /**
       * Format: uuid
       * @description Required when status is completed.
       */
      videoId?: string | null;
      renderTaskId?: string | null;
      /** @example 1.0.0 */
      manifestVersion?: string;
      /** @enum {string} */
      status: "completed" | "failed";
      videoUrl?: string | null;
      coverUrl?: string | null;
      duration?: number | null;
      resolution?: string | null;
      renderLog?: Record<string, unknown> | null;
      error?: components["schemas"]["ErrorDetail"] | null;
    };
    CallbackResponse: {
      /** @example 0 */
      code?: number;
      /** @example received */
      message?: string;
      data?: {
        received?: boolean;
      };
    };
    ModelLogListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: Record<string, never>[];
        total?: number;
      };
    };
    RenderLogListResponse: {
      code?: number;
      message?: string;
      data?: {
        items?: Record<string, never>[];
        total?: number;
      };
    };
  };
  responses: never;
  parameters: {
    ProductId: string;
    TaskId: string;
    VideoId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
